### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by limpep** [spirosikmd/angular2-elastic-input#23]
Hi does this work with angular 4? thanks

**Comment by spirosikmd** [comment]
Hi @limpep! Thank you for your message! I upgraded to latest angular version. It should work. Let me know if you have any issues.

**Comment by limpep** [comment]
@spirosikmd I've tested it with Angular 4.1.3 and it seems to work fine. Thanks.

**Comment by spirosikmd** [comment]
Great @limpep! Good to know!

**Comment by limpep** [comment]
@spirosikmd however look like building to prod using AOT doesn't work getting the following error 

```
ERROR in vendor.b93b17fff90abbb21989.bundle.js from UglifyJs
Unexpected token: name (ElasticInputDirective) [vendor.b93b17fff90abbb21989.bundle.js:23952,6]
```
not sure if this is something from my end.

**Comment by spirosikmd** [comment]
Hey @limpep! Thank you for the info! I will have a look. Haven't tried it with AOT.
