### ISSUE TITLE
Placeholder support

### ISSUE THREAD

**Issue by bartes** [spirosikmd/angular2-elastic-input#27]
Would be super nice to have placeholder support (which is a very common scenario). https://github.com/jacek-pulit/angular-elastic-input/blob/master/src/angular-elastic-input.js#L83

**Comment by spirosikmd** [comment]
Hi @bartes! Thank you for submitting an issue! You are right! It does make sense. I will have a look at it. Feel free to submit a PR if you feel like it anyway :)
