### ISSUE TITLE
Input field get disappear

### ISSUE THREAD

**Issue by arun-maddheshia** [spirosikmd/angular2-elastic-input#55]
When I use @Output to emit updated input value to an object the input field get disappear.

**Comment by spirosikmd** [comment]
Hi @arun-maddheshia! Thank you for submitting this issue. It would help a lot if you provide a way to reproduce this issue, maybe use [codesandbox](https://codesandbox.io/s/angular)?

**Comment by arun-maddheshia** [comment]
@spirosikmd I make fix please review https://github.com/spirosikmd/angular2-elastic-input/pull/56
